server:
  port: 8000
spring:
  application:
    name: microservice-provider-user-with-auth  # 注册到Eureka Server上的应用名称
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2                             #指定数据源类型
    schema: classpath:schema.sql             #指定h2数据库的建表脚本
    data: classpath:data.sql                 #指定H2数据库的数据脚本
logging:
  level:
    root: INFO
    org.heibernate: DEBUG
    org.heibernate.type.dascriptor.sql.BasicBinder: TRACE
    org.heibernate.type.dascriptor.sql.BasicExtractor: TRACE

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true                  #表示将自己的IP注册到Eureka Server。如果不配置该属性或将其设置为false，则表示注册微服务所在操作系统的hsotname到eureka Server
    metadata-map:
      #自定义元数据，key/value可以随便写
      my-metadata: 我自定义的元数据