server:
  port: 8761

eureka:
  client:
    register-with-eureka: false   #表示是否将自己注册到Eureka Server，默认为true，由于当前应用就是Eureka Server，故而设为false
    fetch-registry: false         #表示是否从Eureka Server获取注册信息，morenweitrue
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756