server:
  port: 8761

eureka:
  client:
    register-with-eureka: false   #表示是否将自己注册到Eureka Server，默认为true，由于当前应用就是Eureka Server，故而设为false
    fetch-registry: false         #表示是否从Eureka Server获取注册信息，morenweitrue
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

security:
  basic:
    enabled: true                  # 开启基于HTTP basic的认证
  user:
    name: user                     # 配置登录的账号是user
    password: password123          # 配置登录的密码是password123